---

name: Deploy decklists

on: 
  push: 
    branches: 
      - master

jobs:
  deploy-vkit: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master

      - name: npm install aws-sdk
        run: npm install aws-sdk

      - name: create json
        run: python3 decklist_txt2yaml.py

      - name: sync to s3
        run: aws s3 sync ./json/ s3://res.starwarsccg.org/decklists/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude decklist_txt2yaml.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}







